-- VALIDATED BCEAO FX COLLECTION SEED
-- POSTGRESQL
-- Requires 003, 004, 007 and 005 to be applied first.
-- Seeds only the endpoint, mappings, provider series and collection rules
-- demonstrated by the controlled live run on 2026-08-03.

-- Institutional role definitions required by the BCEAO assignments.
insert into ref.organization_role (
    role_code,
    role_domain,
    name_fr_canonical,
    name_en,
    description,
    can_be_country_scope,
    can_be_zone_scope,
    can_be_regional_scope,
    can_be_continent_scope,
    is_data_provider_role,
    is_regulatory_role,
    is_market_infrastructure_role,
    is_active
)
values
    (
        'CENTRAL_BANK',
        'MONETARY',
        'BANQUE CENTRALE',
        'CENTRAL BANK',
        'AUTORITE RESPONSABLE DE LA POLITIQUE MONETAIRE ET DES STATISTIQUES MONETAIRES.',
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true
    ),
    (
        'FX_REFERENCE_RATE_PROVIDER',
        'FX',
        'FOURNISSEUR DE TAUX DE CHANGE DE REFERENCE',
        'FX REFERENCE RATE PROVIDER',
        'ORGANISATION OFFICIELLE PUBLIANT DES COURS OU TAUX DE CHANGE DE REFERENCE.',
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true
    )
on conflict (role_code) do update
set role_domain = excluded.role_domain,
    name_fr_canonical = excluded.name_fr_canonical,
    name_en = excluded.name_en,
    description = excluded.description,
    can_be_country_scope = excluded.can_be_country_scope,
    can_be_zone_scope = excluded.can_be_zone_scope,
    can_be_regional_scope = excluded.can_be_regional_scope,
    can_be_continent_scope = excluded.can_be_continent_scope,
    is_data_provider_role = excluded.is_data_provider_role,
    is_regulatory_role = excluded.is_regulatory_role,
    is_market_infrastructure_role = excluded.is_market_infrastructure_role,
    is_active = excluded.is_active,
    updated_at = now();

insert into ref.organization (
    organization_id,
    organization_code,
    organization_type,
    name_fr_canonical,
    name_en,
    acronym,
    primary_scope_code,
    primary_country_code,
    primary_zone_code,
    official_website,
    data_portal_url,
    is_public_authority,
    is_market_infrastructure,
    is_data_provider,
    validation_status,
    source_note
)
values (
    '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
    'BCEAO',
    'CENTRAL_BANK',
    'BANQUE CENTRALE DES ETATS DE L AFRIQUE DE L OUEST',
    'CENTRAL BANK OF WEST AFRICAN STATES',
    'BCEAO',
    'UEMOA',
    null,
    'UEMOA',
    'https://www.bceao.int/',
    'https://www.bceao.int/fr',
    true,
    false,
    true,
    'VALIDATED',
    'OFFICIAL_SITE_AND_LIVE_FX_TABLE_VERIFIED_2026_08_03'
)
on conflict (organization_code) do update
set organization_type = excluded.organization_type,
    name_fr_canonical = excluded.name_fr_canonical,
    name_en = excluded.name_en,
    acronym = excluded.acronym,
    primary_scope_code = excluded.primary_scope_code,
    primary_zone_code = excluded.primary_zone_code,
    official_website = excluded.official_website,
    data_portal_url = excluded.data_portal_url,
    is_public_authority = excluded.is_public_authority,
    is_data_provider = excluded.is_data_provider,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into ref.organization_scope_role (
    organization_scope_role_id,
    organization_id,
    role_code,
    scope_entity_code,
    scope_entity_type,
    relationship_role,
    is_primary,
    validation_status,
    source_note
)
values
    (
        '1d934a66-2969-59c8-b93b-c38f91bf9b17',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        'CENTRAL_BANK',
        'UEMOA',
        'MONETARY_ZONE',
        'PRIMARY',
        true,
        'VALIDATED',
        'CANONICAL_UEMOA_CENTRAL_BANK_ASSIGNMENT'
    ),
    (
        'c7ad2cb2-ab70-5bf3-81fa-3ac8e5ada6db',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        'FX_REFERENCE_RATE_PROVIDER',
        'UEMOA',
        'MONETARY_ZONE',
        'PRIMARY',
        true,
        'VALIDATED',
        'LIVE_FX_TABLE_VERIFIED_2026_08_03'
    )
on conflict (organization_scope_role_id) do update
set organization_id = excluded.organization_id,
    role_code = excluded.role_code,
    scope_entity_code = excluded.scope_entity_code,
    scope_entity_type = excluded.scope_entity_type,
    relationship_role = excluded.relationship_role,
    is_primary = excluded.is_primary,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.endpoint (
    endpoint_id,
    endpoint_code,
    organization_id,
    scope_type,
    scope_code,
    endpoint_type,
    url,
    official_url,
    data_portal_url,
    api_base_url,
    access_method,
    auth_required,
    authentication_type,
    file_format,
    file_formats,
    publication_frequency,
    expected_frequency,
    expected_history_start,
    history_start,
    last_verified_at,
    validation_status,
    source_note
)
values (
    '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
    'BCEAO_FX_DAILY',
    '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
    'ZONE',
    'UEMOA',
    'WEB_PAGE',
    'https://www.bceao.int/fr',
    'https://www.bceao.int/fr',
    null,
    null,
    'PUBLIC_WEB',
    false,
    'NONE',
    'HTML',
    array['HTML']::text[],
    'DAILY',
    'DAILY',
    null,
    null,
    '2026-08-03T01:52:02Z'::timestamptz,
    'VALIDATED',
    'LIVE_RUN_30778428536_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206'
)
on conflict (endpoint_code) do update
set organization_id = excluded.organization_id,
    scope_type = excluded.scope_type,
    scope_code = excluded.scope_code,
    endpoint_type = excluded.endpoint_type,
    url = excluded.url,
    official_url = excluded.official_url,
    access_method = excluded.access_method,
    auth_required = excluded.auth_required,
    authentication_type = excluded.authentication_type,
    file_format = excluded.file_format,
    file_formats = excluded.file_formats,
    publication_frequency = excluded.publication_frequency,
    expected_frequency = excluded.expected_frequency,
    last_verified_at = excluded.last_verified_at,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.indicator_source_mapping (
    mapping_id,
    mapping_code,
    scope_type,
    scope_code,
    domain_code,
    indicator_code,
    organization_id,
    organization_role_code,
    endpoint_id,
    provider_series_code,
    provider_series_name,
    frequency_native,
    unit_code,
    currency_code,
    is_primary_source,
    source_priority,
    collection_status,
    validation_status,
    usage_target,
    source_note
)
values
    (
        '5c9d24db-71cb-5ef6-a229-4cd490afdf9e',
        'UEMOA_D09_FX_EUR',
        'ZONE',
        'UEMOA',
        'D09',
        'FX_XOF_EUR',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        'FX_REFERENCE_RATE_PROVIDER',
        '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
        'PS_UEMOA_FX_XOF_EUR',
        'XOF VERS EUR CALCULE DEPUIS LE MIDPOINT BCEAO',
        'DAILY',
        'FX_RATE',
        'XOF',
        true,
        1,
        'COLLECTION_TESTED',
        'VALIDATED',
        array['LOCAL_EUR_CONVERSION']::text[],
        'OBSERVED_EUR_XOF_BUY_SELL_THEN_INVERTED_MIDPOINT'
    ),
    (
        '0c1fb34d-b686-5e16-a7e6-1075b47b7d8b',
        'UEMOA_D09_FX_USD',
        'ZONE',
        'UEMOA',
        'D09',
        'FX_XOF_USD',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        'FX_REFERENCE_RATE_PROVIDER',
        '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
        'PS_UEMOA_FX_XOF_USD',
        'XOF VERS USD CALCULE DEPUIS LE MIDPOINT BCEAO',
        'DAILY',
        'FX_RATE',
        'XOF',
        true,
        1,
        'COLLECTION_TESTED',
        'VALIDATED',
        array['LOCAL_USD_CONVERSION']::text[],
        'OBSERVED_USD_XOF_BUY_SELL_THEN_INVERTED_MIDPOINT'
    )
on conflict (mapping_code) do update
set organization_id = excluded.organization_id,
    organization_role_code = excluded.organization_role_code,
    endpoint_id = excluded.endpoint_id,
    provider_series_code = excluded.provider_series_code,
    provider_series_name = excluded.provider_series_name,
    frequency_native = excluded.frequency_native,
    unit_code = excluded.unit_code,
    currency_code = excluded.currency_code,
    is_primary_source = excluded.is_primary_source,
    source_priority = excluded.source_priority,
    collection_status = excluded.collection_status,
    validation_status = excluded.validation_status,
    usage_target = excluded.usage_target,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.provider_series (
    provider_series_id,
    provider_series_code,
    mapping_code,
    organization_id,
    endpoint_id,
    canonical_indicator_code,
    native_series_code,
    native_series_name,
    native_series_url,
    native_frequency,
    native_unit,
    native_currency_code,
    revision_policy,
    history_status,
    validation_status
)
values
    (
        '41b0ddb2-a1ed-5733-b3e1-a07e249b9753',
        'PS_UEMOA_BCEAO_FX_SNAPSHOT',
        'UEMOA_D09_FX_SNAPSHOT',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
        'FX_XOF_EUR_USD_RAW',
        'BCEAO_FX_DAILY_TABLE',
        'COURS DES DEVISES BCEAO',
        'https://www.bceao.int/fr',
        'DAILY',
        'FX_RATE',
        'XOF',
        'KEEP_ALL_REVISIONS',
        'COLLECTION_TESTED',
        'VALIDATED'
    ),
    (
        '352810a4-a95f-581b-8065-26c6840e5674',
        'PS_UEMOA_FX_XOF_EUR',
        'UEMOA_D09_FX_EUR',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
        'FX_XOF_EUR',
        null,
        'XOF VERS EUR CALCULE DEPUIS LE MIDPOINT BCEAO',
        null,
        'DAILY',
        'FX_RATE',
        'XOF',
        'KEEP_ALL_REVISIONS',
        'COLLECTION_TESTED',
        'VALIDATED'
    ),
    (
        'f9393b91-98dc-5f8d-96cf-a510345dbcf2',
        'PS_UEMOA_FX_XOF_USD',
        'UEMOA_D09_FX_USD',
        '302dbf2d-4a75-5e9f-84eb-d6b5368cf4ab',
        '857a19f9-8c29-5dff-a84c-c0c93a540bf8',
        'FX_XOF_USD',
        null,
        'XOF VERS USD CALCULE DEPUIS LE MIDPOINT BCEAO',
        null,
        'DAILY',
        'FX_RATE',
        'XOF',
        'KEEP_ALL_REVISIONS',
        'COLLECTION_TESTED',
        'VALIDATED'
    )
on conflict (provider_series_code) do update
set mapping_code = excluded.mapping_code,
    organization_id = excluded.organization_id,
    endpoint_id = excluded.endpoint_id,
    canonical_indicator_code = excluded.canonical_indicator_code,
    native_series_code = excluded.native_series_code,
    native_series_name = excluded.native_series_name,
    native_series_url = excluded.native_series_url,
    native_frequency = excluded.native_frequency,
    native_unit = excluded.native_unit,
    native_currency_code = excluded.native_currency_code,
    revision_policy = excluded.revision_policy,
    history_status = excluded.history_status,
    validation_status = excluded.validation_status,
    updated_at = now();

insert into source.collection_specification (
    collection_specification_id,
    collection_specification_code,
    provider_series_id,
    collection_method,
    request_method,
    discovery_rule,
    table_or_selector,
    date_extraction_rule,
    value_extraction_rule,
    number_parsing_rule,
    currency_rule,
    frequency_check,
    expected_publication_lag_days,
    deduplication_key,
    revision_handling,
    raw_artifact_required,
    hash_required,
    parser_version,
    retry_policy,
    quality_check_profile,
    implementation_status,
    validation_status
)
values (
    '11464493-a058-5ff6-98ad-4f0a3ba8d82b',
    'CS_UEMOA_BCEAO_FX_SNAPSHOT',
    '41b0ddb2-a1ed-5733-b3e1-a07e249b9753',
    'HTML_SNAPSHOT',
    'GET',
    'DOWNLOAD_BCEAO_HOME_PAGE_AND_PARSE_FX_TABLE',
    'COURS_DES_DEVISES_TABLE',
    'FRENCH_TEXT_DATE_OR_NUMERIC_DATE',
    'PROVIDER_BUY_AND_SELL_RATES',
    'LOCALE_AWARE_DECIMAL',
    'PRESERVE_PROVIDER_QUOTE_THEN_INVERT_MIDPOINT',
    'DAILY_BUSINESS_DAY_CHECK',
    null,
    'RAW_SHA256|VALUE_DATE|CURRENCY|RATE_TYPE',
    'KEEP_ALL_REVISIONS',
    true,
    true,
    '0.2.0',
    'STANDARD_BACKOFF',
    'FX_BUY_SELL_DATE_AND_LINEAGE_CHECKS',
    'COLLECTION_TESTED',
    'VALIDATED'
)
on conflict (collection_specification_code) do update
set provider_series_id = excluded.provider_series_id,
    collection_method = excluded.collection_method,
    request_method = excluded.request_method,
    discovery_rule = excluded.discovery_rule,
    table_or_selector = excluded.table_or_selector,
    date_extraction_rule = excluded.date_extraction_rule,
    value_extraction_rule = excluded.value_extraction_rule,
    number_parsing_rule = excluded.number_parsing_rule,
    currency_rule = excluded.currency_rule,
    frequency_check = excluded.frequency_check,
    deduplication_key = excluded.deduplication_key,
    revision_handling = excluded.revision_handling,
    raw_artifact_required = excluded.raw_artifact_required,
    hash_required = excluded.hash_required,
    parser_version = excluded.parser_version,
    retry_policy = excluded.retry_policy,
    quality_check_profile = excluded.quality_check_profile,
    implementation_status = excluded.implementation_status,
    validation_status = excluded.validation_status,
    updated_at = now();
