-- BEAC FX COLLECTION SEED
-- POSTGRESQL
-- Requires 003, 004, 007 and 005 to be applied first.
-- Organization, institutional roles and official endpoint are verified.
-- Provider-series and collection statuses remain pending live validation.

insert into ref.organization_role (
    role_code,
    role_domain,
    name_fr_canonical,
    name_en,
    description,
    can_be_country_scope,
    can_be_zone_scope,
    can_be_regional_scope,
    can_be_continent_scope,
    is_data_provider_role,
    is_regulatory_role,
    is_market_infrastructure_role,
    is_active
)
values
    (
        'CENTRAL_BANK',
        'MONETARY',
        'BANQUE CENTRALE',
        'CENTRAL BANK',
        'AUTORITE RESPONSABLE DE LA POLITIQUE MONETAIRE ET DES STATISTIQUES MONETAIRES.',
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true
    ),
    (
        'FX_REFERENCE_RATE_PROVIDER',
        'FX',
        'FOURNISSEUR DE TAUX DE CHANGE DE REFERENCE',
        'FX REFERENCE RATE PROVIDER',
        'ORGANISATION OFFICIELLE PUBLIANT DES COURS OU TAUX DE CHANGE DE REFERENCE.',
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true
    )
on conflict (role_code) do update
set role_domain = excluded.role_domain,
    name_fr_canonical = excluded.name_fr_canonical,
    name_en = excluded.name_en,
    description = excluded.description,
    can_be_country_scope = excluded.can_be_country_scope,
    can_be_zone_scope = excluded.can_be_zone_scope,
    can_be_regional_scope = excluded.can_be_regional_scope,
    can_be_continent_scope = excluded.can_be_continent_scope,
    is_data_provider_role = excluded.is_data_provider_role,
    is_regulatory_role = excluded.is_regulatory_role,
    is_market_infrastructure_role = excluded.is_market_infrastructure_role,
    is_active = excluded.is_active,
    updated_at = now();

insert into ref.organization (
    organization_id,
    organization_code,
    organization_type,
    name_fr_canonical,
    name_en,
    acronym,
    primary_scope_code,
    primary_country_code,
    primary_zone_code,
    official_website,
    data_portal_url,
    is_public_authority,
    is_market_infrastructure,
    is_data_provider,
    validation_status,
    source_note
)
values (
    'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
    'BEAC',
    'CENTRAL_BANK',
    'BANQUE DES ETATS DE L AFRIQUE CENTRALE',
    'BANK OF CENTRAL AFRICAN STATES',
    'BEAC',
    'CEMAC',
    null,
    'CEMAC',
    'https://www.beac.int/',
    'https://www.beac.int/index.php/accueil',
    true,
    false,
    true,
    'VALIDATED',
    'OFFICIAL_SITE_AND_FX_TABLE_VERIFIED_2026_08_03'
)
on conflict (organization_code) do update
set organization_type = excluded.organization_type,
    name_fr_canonical = excluded.name_fr_canonical,
    name_en = excluded.name_en,
    acronym = excluded.acronym,
    primary_scope_code = excluded.primary_scope_code,
    primary_zone_code = excluded.primary_zone_code,
    official_website = excluded.official_website,
    data_portal_url = excluded.data_portal_url,
    is_public_authority = excluded.is_public_authority,
    is_data_provider = excluded.is_data_provider,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into ref.organization_scope_role (
    organization_scope_role_id,
    organization_id,
    role_code,
    scope_entity_code,
    scope_entity_type,
    relationship_role,
    is_primary,
    validation_status,
    source_note
)
values
    (
        '0b2f53a9-e9fd-5fc2-a000-8af692c534c2',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'CENTRAL_BANK',
        'CEMAC',
        'MONETARY_ZONE',
        'PRIMARY',
        true,
        'VALIDATED',
        'CANONICAL_CEMAC_CENTRAL_BANK_ASSIGNMENT'
    ),
    (
        '6758794f-166e-5067-ac43-cd6d86aa1315',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'FX_REFERENCE_RATE_PROVIDER',
        'CEMAC',
        'MONETARY_ZONE',
        'PRIMARY',
        true,
        'VALIDATED',
        'OFFICIAL_FX_TABLE_VERIFIED_2026_08_03'
    )
on conflict (organization_scope_role_id) do update
set organization_id = excluded.organization_id,
    role_code = excluded.role_code,
    scope_entity_code = excluded.scope_entity_code,
    scope_entity_type = excluded.scope_entity_type,
    relationship_role = excluded.relationship_role,
    is_primary = excluded.is_primary,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.endpoint (
    endpoint_id,
    endpoint_code,
    organization_id,
    scope_type,
    scope_code,
    endpoint_type,
    url,
    official_url,
    data_portal_url,
    api_base_url,
    access_method,
    auth_required,
    authentication_type,
    file_format,
    file_formats,
    publication_frequency,
    expected_frequency,
    expected_history_start,
    history_start,
    last_verified_at,
    validation_status,
    source_note
)
values (
    'cb5518cd-236c-5ded-8941-56f09eb74bdc',
    'BEAC_FX_DAILY',
    'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
    'ZONE',
    'CEMAC',
    'WEB_PAGE',
    'https://www.beac.int/index.php/accueil',
    'https://www.beac.int/index.php/accueil',
    null,
    null,
    'PUBLIC_WEB',
    false,
    'NONE',
    'HTML',
    array['HTML']::text[],
    'DAILY',
    'DAILY',
    null,
    null,
    null,
    'VALIDATED',
    'OFFICIAL_PAGE_AND_FX_TABLE_VERIFIED_2026_08_03_LIVE_COLLECTOR_TEST_PENDING'
)
on conflict (endpoint_code) do update
set organization_id = excluded.organization_id,
    scope_type = excluded.scope_type,
    scope_code = excluded.scope_code,
    endpoint_type = excluded.endpoint_type,
    url = excluded.url,
    official_url = excluded.official_url,
    access_method = excluded.access_method,
    auth_required = excluded.auth_required,
    authentication_type = excluded.authentication_type,
    file_format = excluded.file_format,
    file_formats = excluded.file_formats,
    publication_frequency = excluded.publication_frequency,
    expected_frequency = excluded.expected_frequency,
    validation_status = excluded.validation_status,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.indicator_source_mapping (
    mapping_id,
    mapping_code,
    scope_type,
    scope_code,
    domain_code,
    indicator_code,
    organization_id,
    organization_role_code,
    endpoint_id,
    provider_series_code,
    provider_series_name,
    frequency_native,
    unit_code,
    currency_code,
    is_primary_source,
    source_priority,
    collection_status,
    validation_status,
    usage_target,
    source_note
)
values
    (
        'ed45fa2d-6cca-5d7b-9f8f-370f49b441a9',
        'CEMAC_D09_FX_EUR',
        'ZONE',
        'CEMAC',
        'D09',
        'FX_XAF_EUR',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'FX_REFERENCE_RATE_PROVIDER',
        'cb5518cd-236c-5ded-8941-56f09eb74bdc',
        'PS_CEMAC_FX_XAF_EUR',
        'XAF VERS EUR CALCULE DEPUIS LE MIDPOINT BEAC',
        'DAILY',
        'FX_RATE',
        'XAF',
        true,
        1,
        'URL_LINKED',
        'VALIDATED',
        array['LOCAL_EUR_CONVERSION']::text[],
        'OBSERVED_EUR_XAF_BUY_SELL_THEN_INVERTED_MIDPOINT_LIVE_TEST_PENDING'
    ),
    (
        '16d59b96-a6ed-5fa6-9997-3e9c74ddb94e',
        'CEMAC_D09_FX_USD',
        'ZONE',
        'CEMAC',
        'D09',
        'FX_XAF_USD',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'FX_REFERENCE_RATE_PROVIDER',
        'cb5518cd-236c-5ded-8941-56f09eb74bdc',
        'PS_CEMAC_FX_XAF_USD',
        'XAF VERS USD CALCULE DEPUIS LE MIDPOINT BEAC',
        'DAILY',
        'FX_RATE',
        'XAF',
        true,
        1,
        'URL_LINKED',
        'VALIDATED',
        array['LOCAL_USD_CONVERSION']::text[],
        'OBSERVED_USD_XAF_BUY_SELL_THEN_INVERTED_MIDPOINT_LIVE_TEST_PENDING'
    )
on conflict (mapping_code) do update
set organization_id = excluded.organization_id,
    organization_role_code = excluded.organization_role_code,
    endpoint_id = excluded.endpoint_id,
    provider_series_code = excluded.provider_series_code,
    provider_series_name = excluded.provider_series_name,
    frequency_native = excluded.frequency_native,
    unit_code = excluded.unit_code,
    currency_code = excluded.currency_code,
    is_primary_source = excluded.is_primary_source,
    source_priority = excluded.source_priority,
    collection_status = excluded.collection_status,
    validation_status = excluded.validation_status,
    usage_target = excluded.usage_target,
    source_note = excluded.source_note,
    updated_at = now();

insert into source.provider_series (
    provider_series_id,
    provider_series_code,
    mapping_code,
    organization_id,
    endpoint_id,
    canonical_indicator_code,
    native_series_code,
    native_series_name,
    native_series_url,
    native_frequency,
    native_unit,
    native_currency_code,
    revision_policy,
    history_status,
    validation_status
)
values
    (
        '60058d6f-608e-5221-abd3-86585386a4bb',
        'PS_CEMAC_BEAC_FX_SNAPSHOT',
        'CEMAC_D09_FX_SNAPSHOT',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'cb5518cd-236c-5ded-8941-56f09eb74bdc',
        'FX_XAF_EUR_USD_RAW',
        'BEAC_FX_DAILY_TABLE',
        'TAUX INDICATIFS DE CHANGE BEAC',
        'https://www.beac.int/index.php/accueil',
        'DAILY',
        'FX_RATE',
        'XAF',
        'KEEP_ALL_REVISIONS',
        'COLLECTOR_IMPLEMENTED',
        'PENDING'
    ),
    (
        'b1da9ec4-7672-5214-a117-37726a7c40f6',
        'PS_CEMAC_FX_XAF_EUR',
        'CEMAC_D09_FX_EUR',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'cb5518cd-236c-5ded-8941-56f09eb74bdc',
        'FX_XAF_EUR',
        null,
        'XAF VERS EUR CALCULE DEPUIS LE MIDPOINT BEAC',
        null,
        'DAILY',
        'FX_RATE',
        'XAF',
        'KEEP_ALL_REVISIONS',
        'COLLECTOR_IMPLEMENTED',
        'PENDING'
    ),
    (
        '29740f5e-fbd7-53f6-873c-8ca5a223ab39',
        'PS_CEMAC_FX_XAF_USD',
        'CEMAC_D09_FX_USD',
        'af6d3e9d-95fd-50ca-8880-6f58f564bdd4',
        'cb5518cd-236c-5ded-8941-56f09eb74bdc',
        'FX_XAF_USD',
        null,
        'XAF VERS USD CALCULE DEPUIS LE MIDPOINT BEAC',
        null,
        'DAILY',
        'FX_RATE',
        'XAF',
        'KEEP_ALL_REVISIONS',
        'COLLECTOR_IMPLEMENTED',
        'PENDING'
    )
on conflict (provider_series_code) do update
set mapping_code = excluded.mapping_code,
    organization_id = excluded.organization_id,
    endpoint_id = excluded.endpoint_id,
    canonical_indicator_code = excluded.canonical_indicator_code,
    native_series_code = excluded.native_series_code,
    native_series_name = excluded.native_series_name,
    native_series_url = excluded.native_series_url,
    native_frequency = excluded.native_frequency,
    native_unit = excluded.native_unit,
    native_currency_code = excluded.native_currency_code,
    revision_policy = excluded.revision_policy,
    history_status = excluded.history_status,
    validation_status = excluded.validation_status,
    updated_at = now();

insert into source.collection_specification (
    collection_specification_id,
    collection_specification_code,
    provider_series_id,
    collection_method,
    request_method,
    discovery_rule,
    table_or_selector,
    date_extraction_rule,
    value_extraction_rule,
    number_parsing_rule,
    currency_rule,
    frequency_check,
    expected_publication_lag_days,
    deduplication_key,
    revision_handling,
    raw_artifact_required,
    hash_required,
    parser_version,
    retry_policy,
    quality_check_profile,
    implementation_status,
    validation_status
)
values (
    '128bb2f4-ff2d-5633-8e13-b5e1cb72c88d',
    'CS_CEMAC_BEAC_FX_SNAPSHOT',
    '60058d6f-608e-5221-abd3-86585386a4bb',
    'HTML_SNAPSHOT',
    'GET',
    'DOWNLOAD_BEAC_HOME_PAGE_AND_PARSE_FX_TABLE',
    'TAUX_INDICATIFS_DE_CHANGE_TABLE',
    'FRENCH_TEXT_DATE_OR_NUMERIC_DATE',
    'PROVIDER_PAIR_BUY_AND_SELL_RATES',
    'LOCALE_AWARE_DECIMAL',
    'PRESERVE_PROVIDER_QUOTE_THEN_INVERT_MIDPOINT',
    'DAILY_BUSINESS_DAY_CHECK',
    null,
    'RAW_SHA256|VALUE_DATE|PAIR|RATE_TYPE',
    'KEEP_ALL_REVISIONS',
    true,
    true,
    '0.1.0',
    'STANDARD_BACKOFF',
    'FX_PAIR_BUY_SELL_DATE_AND_LINEAGE_CHECKS',
    'COLLECTOR_IMPLEMENTED',
    'PENDING'
)
on conflict (collection_specification_code) do update
set provider_series_id = excluded.provider_series_id,
    collection_method = excluded.collection_method,
    request_method = excluded.request_method,
    discovery_rule = excluded.discovery_rule,
    table_or_selector = excluded.table_or_selector,
    date_extraction_rule = excluded.date_extraction_rule,
    value_extraction_rule = excluded.value_extraction_rule,
    number_parsing_rule = excluded.number_parsing_rule,
    currency_rule = excluded.currency_rule,
    frequency_check = excluded.frequency_check,
    deduplication_key = excluded.deduplication_key,
    revision_handling = excluded.revision_handling,
    raw_artifact_required = excluded.raw_artifact_required,
    hash_required = excluded.hash_required,
    parser_version = excluded.parser_version,
    retry_policy = excluded.retry_policy,
    quality_check_profile = excluded.quality_check_profile,
    implementation_status = excluded.implementation_status,
    validation_status = excluded.validation_status,
    updated_at = now();
