-- GENERATED FILE: DO NOT EDIT.
-- Authoring source: data/reference/VALIDATED_FX_REFERENCE_REGISTRY.csv
-- PostgreSQL remains the runtime source of truth after application.

update ref.organization set official_website='https://www.bceao.int', data_portal_url='https://www.bceao.int/fr', validation_status='VALIDATED', source_note='EVIDENCE_CTE_BCEAO_FX_20260731_001_RUN_30777722357_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206_VALUE_DATE_2026_07_31', updated_at=now() where organization_code='BCEAO';

insert into source.endpoint(endpoint_id,endpoint_code,organization_id,scope_type,scope_code,endpoint_type,url,official_url,access_method,auth_required,file_formats,expected_frequency,last_verified_at,validation_status,source_note) select '857a19f9-8c29-5dff-a84c-c0c93a540bf8'::uuid,'BCEAO_FX_DAILY',organization_id,'ZONE','UEMOA','WEB_PAGE','https://www.bceao.int/fr','https://www.bceao.int/fr','PUBLIC_WEB',false,array['HTML']::text[],'DAILY','2026-08-03T01:47:58+00:00'::timestamptz,'VALIDATED','EVIDENCE_CTE_BCEAO_FX_20260731_001_RUN_30777722357_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206_VALUE_DATE_2026_07_31' from ref.organization where organization_code='BCEAO' on conflict(endpoint_code) do update set organization_id=excluded.organization_id,scope_type=excluded.scope_type,scope_code=excluded.scope_code,endpoint_type=excluded.endpoint_type,url=excluded.url,official_url=excluded.official_url,access_method=excluded.access_method,auth_required=excluded.auth_required,file_formats=excluded.file_formats,expected_frequency=excluded.expected_frequency,last_verified_at=excluded.last_verified_at,validation_status=excluded.validation_status,source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select 'bf358f0e-358c-5418-a933-c26734cceadf'::uuid,'UEMOA_D09_FX_SNAPSHOT','ZONE','UEMOA','D09','FX_XOF_EUR_USD_RAW',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_UEMOA_BCEAO_FX_SNAPSHOT','DAILY','FX_RATE','XOF',true,1,'COLLECTION_TESTED','VALIDATED',array['RAW_FX_SNAPSHOT']::text[],'EVIDENCE_CTE_BCEAO_FX_20260731_001_RUN_30777722357_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select '5c9d24db-71cb-5ef6-a229-4cd490afdf9e'::uuid,'UEMOA_D09_FX_EUR','ZONE','UEMOA','D09','FX_XOF_EUR',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_UEMOA_FX_XOF_EUR','DAILY','FX_RATE','XOF',true,1,'COLLECTION_TESTED','VALIDATED',array['LOCAL_EUR_CONVERSION']::text[],'EVIDENCE_CTE_BCEAO_FX_20260731_001_RUN_30777722357_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select '0c1fb34d-b686-5e16-a7e6-1075b47b7d8b'::uuid,'UEMOA_D09_FX_USD','ZONE','UEMOA','D09','FX_XOF_USD',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_UEMOA_FX_XOF_USD','DAILY','FX_RATE','XOF',true,1,'COLLECTION_TESTED','VALIDATED',array['LOCAL_USD_CONVERSION']::text[],'EVIDENCE_CTE_BCEAO_FX_20260731_001_RUN_30777722357_SHA256_76690835F3A8CD808880C80AEEC2E9F078CB6A76C9FAE0D8EBE1278AD2421206_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select '41b0ddb2-a1ed-5733-b3e1-a07e249b9753'::uuid,'PS_UEMOA_BCEAO_FX_SNAPSHOT','UEMOA_D09_FX_SNAPSHOT',o.organization_id,e.endpoint_id,'FX_XOF_EUR_USD_RAW','https://www.bceao.int/fr','DAILY','FX_RATE','XOF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select '352810a4-a95f-581b-8065-26c6840e5674'::uuid,'PS_UEMOA_FX_XOF_EUR','UEMOA_D09_FX_EUR',o.organization_id,e.endpoint_id,'FX_XOF_EUR',null,'DAILY','FX_RATE','XOF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select 'f9393b91-98dc-5f8d-96cf-a510345dbcf2'::uuid,'PS_UEMOA_FX_XOF_USD','UEMOA_D09_FX_USD',o.organization_id,e.endpoint_id,'FX_XOF_USD',null,'DAILY','FX_RATE','XOF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BCEAO_FX_DAILY' where o.organization_code='BCEAO' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select '11464493-a058-5ff6-98ad-4f0a3ba8d82b'::uuid,'CS_UEMOA_BCEAO_FX_SNAPSHOT',provider_series_id,'HTML_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','COURS_DES_DEVISES_TABLE','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XOF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_BUY_SELL_DATE_SHA256_IDEMPOTENCE_AND_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_UEMOA_BCEAO_FX_SNAPSHOT' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select '7218c489-bada-5dac-a4c1-3ee344df01cd'::uuid,'CS_UEMOA_FX_XOF_EUR',provider_series_id,'DERIVED_FROM_VALIDATED_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','PROVIDER_BUY_SELL_FROM_SHARED_SNAPSHOT','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XOF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_BUY_SELL_DATE_SHA256_AND_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_UEMOA_FX_XOF_EUR' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select 'ef75fd8e-889d-5e76-8045-f037a3e1ddc8'::uuid,'CS_UEMOA_FX_XOF_USD',provider_series_id,'DERIVED_FROM_VALIDATED_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','PROVIDER_BUY_SELL_FROM_SHARED_SNAPSHOT','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XOF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_BUY_SELL_DATE_SHA256_AND_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_UEMOA_FX_XOF_USD' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

update ref.organization set official_website='https://www.beac.int/', data_portal_url='https://www.beac.int/index.php/accueil', validation_status='VALIDATED', source_note='EVIDENCE_CTE_BEAC_FX_20260731_001_RUN_30779605759_SHA256_C93BE111A3997C913917B5AAE425A02FB575FE0B39BFDA67953E237E0A11C23C_VALUE_DATE_2026_07_31', updated_at=now() where organization_code='BEAC';

insert into source.endpoint(endpoint_id,endpoint_code,organization_id,scope_type,scope_code,endpoint_type,url,official_url,access_method,auth_required,file_formats,expected_frequency,last_verified_at,validation_status,source_note) select 'cb5518cd-236c-5ded-8941-56f09eb74bdc'::uuid,'BEAC_FX_DAILY',organization_id,'ZONE','CEMAC','WEB_PAGE','https://www.beac.int/index.php/accueil','https://www.beac.int/index.php/accueil','PUBLIC_WEB',false,array['HTML']::text[],'DAILY','2026-08-03T02:34:40+00:00'::timestamptz,'VALIDATED','EVIDENCE_CTE_BEAC_FX_20260731_001_RUN_30779605759_SHA256_C93BE111A3997C913917B5AAE425A02FB575FE0B39BFDA67953E237E0A11C23C_VALUE_DATE_2026_07_31' from ref.organization where organization_code='BEAC' on conflict(endpoint_code) do update set organization_id=excluded.organization_id,scope_type=excluded.scope_type,scope_code=excluded.scope_code,endpoint_type=excluded.endpoint_type,url=excluded.url,official_url=excluded.official_url,access_method=excluded.access_method,auth_required=excluded.auth_required,file_formats=excluded.file_formats,expected_frequency=excluded.expected_frequency,last_verified_at=excluded.last_verified_at,validation_status=excluded.validation_status,source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select '286015a8-e416-5f4c-8d96-192641c1f799'::uuid,'CEMAC_D09_FX_SNAPSHOT','ZONE','CEMAC','D09','FX_XAF_EUR_USD_RAW',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_CEMAC_BEAC_FX_SNAPSHOT','DAILY','FX_RATE','XAF',true,1,'COLLECTION_TESTED','VALIDATED',array['RAW_FX_SNAPSHOT']::text[],'EVIDENCE_CTE_BEAC_FX_20260731_001_RUN_30779605759_SHA256_C93BE111A3997C913917B5AAE425A02FB575FE0B39BFDA67953E237E0A11C23C_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select 'ed45fa2d-6cca-5d7b-9f8f-370f49b441a9'::uuid,'CEMAC_D09_FX_EUR','ZONE','CEMAC','D09','FX_XAF_EUR',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_CEMAC_FX_XAF_EUR','DAILY','FX_RATE','XAF',true,1,'COLLECTION_TESTED','VALIDATED',array['LOCAL_EUR_CONVERSION']::text[],'EVIDENCE_CTE_BEAC_FX_20260731_001_RUN_30779605759_SHA256_C93BE111A3997C913917B5AAE425A02FB575FE0B39BFDA67953E237E0A11C23C_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.indicator_source_mapping(mapping_id,mapping_code,scope_type,scope_code,domain_code,indicator_code,organization_id,organization_role_code,endpoint_id,provider_series_code,frequency_native,unit_code,currency_code,is_primary_source,source_priority,collection_status,validation_status,usage_target,source_note) select '16d59b96-a6ed-5fa6-9997-3e9c74ddb94e'::uuid,'CEMAC_D09_FX_USD','ZONE','CEMAC','D09','FX_XAF_USD',o.organization_id,'FX_REFERENCE_RATE_PROVIDER',e.endpoint_id,'PS_CEMAC_FX_XAF_USD','DAILY','FX_RATE','XAF',true,1,'COLLECTION_TESTED','VALIDATED',array['LOCAL_USD_CONVERSION']::text[],'EVIDENCE_CTE_BEAC_FX_20260731_001_RUN_30779605759_SHA256_C93BE111A3997C913917B5AAE425A02FB575FE0B39BFDA67953E237E0A11C23C_VALUE_DATE_2026_07_31' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(mapping_code) do update set endpoint_id=excluded.endpoint_id,provider_series_code=excluded.provider_series_code,collection_status='COLLECTION_TESTED',validation_status='VALIDATED',source_note=excluded.source_note,updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select '60058d6f-608e-5221-abd3-86585386a4bb'::uuid,'PS_CEMAC_BEAC_FX_SNAPSHOT','CEMAC_D09_FX_SNAPSHOT',o.organization_id,e.endpoint_id,'FX_XAF_EUR_USD_RAW','https://www.beac.int/index.php/accueil','DAILY','FX_RATE','XAF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select 'b1da9ec4-7672-5214-a117-37726a7c40f6'::uuid,'PS_CEMAC_FX_XAF_EUR','CEMAC_D09_FX_EUR',o.organization_id,e.endpoint_id,'FX_XAF_EUR',null,'DAILY','FX_RATE','XAF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.provider_series(provider_series_id,provider_series_code,mapping_code,organization_id,endpoint_id,canonical_indicator_code,native_series_url,native_frequency,native_unit,native_currency_code,revision_policy,history_status,validation_status) select '29740f5e-fbd7-53f6-873c-8ca5a223ab39'::uuid,'PS_CEMAC_FX_XAF_USD','CEMAC_D09_FX_USD',o.organization_id,e.endpoint_id,'FX_XAF_USD',null,'DAILY','FX_RATE','XAF','KEEP_ALL_REVISIONS','COLLECTION_TESTED','VALIDATED' from ref.organization o join source.endpoint e on e.endpoint_code='BEAC_FX_DAILY' where o.organization_code='BEAC' on conflict(provider_series_code) do update set mapping_code=excluded.mapping_code,organization_id=excluded.organization_id,endpoint_id=excluded.endpoint_id,canonical_indicator_code=excluded.canonical_indicator_code,native_series_url=excluded.native_series_url,history_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select '128bb2f4-ff2d-5633-8e13-b5e1cb72c88d'::uuid,'CS_CEMAC_BEAC_FX_SNAPSHOT',provider_series_id,'HTML_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','DIV.taux_de_change|TABLE_FALLBACK','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XAF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_DIV_BLOCK_BUY_SELL_DATE_SHA256_IDEMPOTENCE_AND_POSTGRES_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_CEMAC_BEAC_FX_SNAPSHOT' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select '6987bf00-2c1e-5f37-accc-e6a5f5028215'::uuid,'CS_CEMAC_FX_XAF_EUR',provider_series_id,'DERIVED_FROM_VALIDATED_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','PROVIDER_BUY_SELL_FROM_SHARED_SNAPSHOT','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XAF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_BUY_SELL_DATE_SHA256_AND_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_CEMAC_FX_XAF_EUR' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

insert into source.collection_specification(collection_specification_id,collection_specification_code,provider_series_id,collection_method,request_method,discovery_rule,table_or_selector,date_extraction_rule,value_extraction_rule,number_parsing_rule,currency_rule,frequency_check,deduplication_key,revision_handling,raw_artifact_required,hash_required,parser_version,retry_policy,quality_check_profile,implementation_status,validation_status) select 'cfb3e239-9b1e-5955-b19f-cb71d5e58b6e'::uuid,'CS_CEMAC_FX_XAF_USD',provider_series_id,'DERIVED_FROM_VALIDATED_SNAPSHOT','GET','USE_GOVERNED_VALIDATED_FX_REGISTRY','PROVIDER_BUY_SELL_FROM_SHARED_SNAPSHOT','SOURCE_VALUE_DATE','PRESERVE_BUY_SELL_AND_INVERT_MIDPOINT','LOCALE_AWARE_DECIMAL','XAF_TO_EUR_USD_WITH_LINEAGE','DAILY_BUSINESS_DAY_CHECK','RAW_SHA256|VALUE_DATE|SERIES','KEEP_ALL_REVISIONS',true,true,'0.2.0','STANDARD_BACKOFF','FX_BUY_SELL_DATE_SHA256_AND_LINEAGE_CHECKS','COLLECTION_TESTED','VALIDATED' from source.provider_series where provider_series_code='PS_CEMAC_FX_XAF_USD' on conflict(collection_specification_code) do update set provider_series_id=excluded.provider_series_id,collection_method=excluded.collection_method,table_or_selector=excluded.table_or_selector,parser_version=excluded.parser_version,quality_check_profile=excluded.quality_check_profile,implementation_status='COLLECTION_TESTED',validation_status='VALIDATED',updated_at=now();

-- Snapshot pilots only: no PARTIAL_HISTORY_LOADED or COMPLETE_HISTORY_LOADED claim.
